import { useState } from 'react'
import './App.css';
import Component from './Component'


function App() {
  const [ showComponent, setShowComponent ] = useState(true)
  
  const display = showComponent
    ? <Component />
    : ""
  
  return (
    <div className="App">
      <button
        onClick={() => setShowComponent(!showComponent)}
      >
        Toggle component
      </button>
      <p>Open the Console to see the messages generated by useEffect</p>
      {display}
    </div>
  );
}

export default App;
